// import { Geist, Geist_Mono } from "next/font/google";
// import "/globals.css";
// import "../../styles/globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// ==================================================================================

// 'use client';
// // import { QueryClientProvider } from '@tanstack/react-query';
// // import { queryClient } from '../utils/queryClient';

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body  className="__variable_5cfdac __variable_9a8899 antialiased">
//         {/* <QueryClientProvider client={queryClient}> */}
//           {children}
//         {/* </QueryClientProvider> */}
//       </body>
//     </html>
//   );
// }

// =====================================================================================

'use client';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}